---
- name: Setup tasks.

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"

